import {
  countryISOMapping,
  isISO2,
  ISO,
  ISO2,
} from '@ocean/shared/utils/iso-mapper';

export const currencyISO3 = {
  ARE: 'AED',
  AFG: 'AFN',
  ALB: 'ALL',
  ARM: 'AMD',
  AGO: 'AOA',
  ARG: 'ARS',
  AUS: 'AUD',
  KIR: 'AUD',
  NRU: 'AUD',
  TUV: 'AUD',
  AZE: 'AZN',
  BIH: 'BAM',
  BRB: 'BBD',
  BGD: 'BDT',
  BGR: 'BGN',
  BHR: 'BHD',
  BDI: 'BIF',
  BRN: 'BND',
  BOL: 'BOB',
  BRA: 'BRL',
  BHS: 'BSD',
  BTN: 'BTN',
  BWA: 'BWP',
  BLR: 'BYN',
  BLZ: 'BZD',
  CAN: 'CAD',
  COD: 'CDF',
  GIB: 'GIP',
  HKG: 'HKD',
  LIE: 'CHF',
  CHE: 'CHF',
  CHL: 'CLP',
  CHN: 'CNY',
  COL: 'COP',
  CRI: 'CRC',
  CUB: 'CUP',
  CPV: 'CVE',
  CZE: 'CZK',
  DJI: 'DJF',
  DNK: 'DKK',
  DOM: 'DOP',
  DZA: 'DZD',
  EGY: 'EGP',
  ERI: 'ERN',
  ETH: 'ETB',
  AND: 'EUR',
  AUT: 'EUR',
  BEL: 'EUR',
  HRV: 'EUR',
  CYP: 'EUR',
  EST: 'EUR',
  FIN: 'EUR',
  FRA: 'EUR',
  DEU: 'EUR',
  GRC: 'EUR',
  IRL: 'EUR',
  ITA: 'EUR',
  LVA: 'EUR',
  LTU: 'EUR',
  LUX: 'EUR',
  MLT: 'EUR',
  MCO: 'EUR',
  MNE: 'EUR',
  NLD: 'EUR',
  PRT: 'EUR',
  SMR: 'EUR',
  SVK: 'EUR',
  SVN: 'EUR',
  ESP: 'EUR',
  VAT: 'EUR',
  FJI: 'FJD',
  GBR: 'GBP',
  GEO: 'GEL',
  GHA: 'GHS',
  GMB: 'GMD',
  GIN: 'GNF',
  GTM: 'GTQ',
  GUY: 'GYD',
  HND: 'HNL',
  HTI: 'HTG',
  HUN: 'HUF',
  IDN: 'IDR',
  ISR: 'ILS',
  PSE: 'ILS',
  IND: 'INR',
  IRQ: 'IQD',
  IRN: 'IRR',
  ISL: 'ISK',
  JAM: 'JMD',
  JOR: 'JOD',
  JPN: 'JPY',
  KEN: 'KES',
  KGZ: 'KGS',
  KHM: 'KHR',
  COM: 'KMF',
  PRK: 'KPW',
  KOR: 'KRW',
  KWT: 'KWD',
  KAZ: 'KZT',
  LAO: 'LAK',
  LBN: 'LBP',
  LKA: 'LKR',
  LBR: 'LRD',
  LSO: 'LSL',
  LBY: 'LYD',
  MAR: 'MAD',
  MDA: 'MDL',
  MDG: 'MGA',
  MKD: 'MKD',
  MMR: 'MMK',
  MNG: 'MNT',
  MRT: 'MRO',
  MUS: 'MUR',
  MDV: 'MVR',
  MWI: 'MWK',
  MEX: 'MXN',
  MYS: 'MYR',
  MOZ: 'MZN',
  NAM: 'NAD',
  NGA: 'NGN',
  NIC: 'NIO',
  NOR: 'NOK',
  NPL: 'NPR',
  NZL: 'NZD',
  OMN: 'OMR',
  PAN: 'PAB',
  PER: 'PEN',
  PNG: 'PGK',
  PHL: 'PHP',
  PAK: 'PKR',
  POL: 'PLN',
  PRY: 'PYG',
  QAT: 'QAR',
  ROU: 'RON',
  SRB: 'RSD',
  RUS: 'RUB',
  RWA: 'RWF',
  SAU: 'SAR',
  SLB: 'SBD',
  SYC: 'SCR',
  SDN: 'SDG',
  SWE: 'SEK',
  SGP: 'SGD',
  SLE: 'SLL',
  SOM: 'SOS',
  SUR: 'SRD',
  SSD: 'SSP',
  STP: 'STD',
  SYR: 'SYP',
  SWZ: 'SZL',
  THA: 'THB',
  TJK: 'TJS',
  TKM: 'TMT',
  TUN: 'TND',
  TON: 'TOP',
  TUR: 'TRY',
  TTO: 'TTD',
  TWN: 'TWD',
  TZA: 'TZS',
  UKR: 'UAH',
  UGA: 'UGX',
  TLS: 'USD',
  ECU: 'USD',
  SLV: 'USD',
  MHL: 'USD',
  FSM: 'USD',
  PLW: 'USD',
  USA: 'USD',
  ZWE: 'USD',
  URY: 'UYU',
  UZB: 'UZS',
  VEN: 'VEF',
  VNM: 'VND',
  VUT: 'VUV',
  WSM: 'WST',
  CMR: 'XAF',
  CAF: 'XAF',
  TCD: 'XAF',
  GNQ: 'XAF',
  GAB: 'XAF',
  COG: 'XAF',
  ATG: 'XCD',
  DMA: 'XCD',
  GRD: 'XCD',
  KNA: 'XCD',
  LCA: 'XCD',
  VCT: 'XCD',
  BEN: 'XOF',
  BFA: 'XOF',
  GNB: 'XOF',
  CIV: 'XOF',
  MLI: 'XOF',
  NER: 'XOF',
  SEN: 'XOF',
  TGO: 'XOF',
  YEM: 'YER',
  ZAF: 'ZAR',
  ZMB: 'ZMW',
};

const currencyISO2 = Object.entries(currencyISO3).reduce(
  (acc, [key, value]) => {
    return {
      ...acc,
      [countryISOMapping[key]]: value,
    };
  },
  {} as Record<ISO2, keyof typeof currencyISO3>
);

export const getCurrencyList = () =>
  Array.from(
    new Set(Object.entries(currencyISO3).map(([_, value]) => value))
  ).sort((a, b) => a.localeCompare(b));

export const getCurrencyByCountry = (iso: ISO): string => {
  if (isISO2(iso)) {
    return currencyISO2?.[iso] ?? currencyISO2.US;
  }

  return currencyISO3?.[iso] ?? currencyISO3.USA;
};
