name: Playwright Tests
on:
  push:
    branches: [ master, qa ]
jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - name: Cache playwright binaries - restore
      uses: actions/cache@v3
      id: playwright-cache-restore
      with:
        path: |
          ~/Library/Caches/ms-playwright
          ~/.cache/ms-playwright
          playwright/node_modules
        key: playwright-${{ hashFiles('playwright/package-lock.json') }}
    - name: Install dependencies
      run: |
        npm ci
      working-directory: ./playwright
    - name: Install playwright deps
      if: steps.playwright-cache-restore.outputs.cache-hit != 'true'
      run: |
        npx playwright install --with-deps
      working-directory: ./playwright
    - name: Run Playwright tests
      run: npm run test
      working-directory: ./playwright
      env:
        CI: true
        MAILINATOR_KEY: ${{ secrets.MAILINATOR_API_KEY }}
    - name: Cache playwright binaries - save
      uses: actions/cache@v3
      id: playwright-cache-save
      with:
        path: |
          ~/Library/Caches/ms-playwright
          ~/.cache/ms-playwright
          playwright/node_modules
        key: playwright-${{ hashFiles('playwright/package-lock.json') }}
        restore-keys: |
          playwright-
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: |
          ./playwright/playwright-report
          ./playwright/test-results
        retention-days: 30
